# Profile information
name: hapiest
title: hapiest
description: "Website for the hapiest project"
permalink: ':title/'
baseurl: "/hapiest" # the subpath of your site, e.g. /blog
url: "jkarns275.github.io/hapiest" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github: github.com/jkarns275

# Contact form
email: jkarns@oswego.edu

# Paginate
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
